# Generated by Django 4.1.4 on 2022-12-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_description_question_variant_out_put_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
